name: Create package

on:
  workflow_call:
    inputs:
      deployment:
        required: false
        type: string
        default: "development"
      file:
        required: false
        type: string
        default: "Dockerfile"
      context:
        required: false
        type: string
        default: "."
      registry:
        required: false
        type: string
        default: "docker.pkg.github.com"
      username:
        required: false
        type: string
        default: $GITHUB_ACTOR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Semversioner
        run: pip install semversioner

      - name: Get version
        run: |
          if [ ${{ inputs.deployment }} = "development" ]; then
            TAG=$(echo $GITHUB_REF | cut -d "/" -f 3)
          else
            TAG=$(semversioner current-version)
          fi
          
          if [ ${{ inputs.tags }} ]; then
            DOCKER_TAG="${{ inputs.tags }}"
          else
            REPO=$(echo ${{ github.repository }})
            DOCKER_TAG=$(echo "docker.pkg.github.com/$REPO/$TAG")
          fi
 
          echo "DOCKER_TAG="${DOCKER_TAG,,}"" >> $GITHUB_ENV
#
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Extract artifacts
        run: tar -xf dist.tar.gz
#
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.BOT_ACCESS_TOKEN }}"
#
      - name: Build image and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          tags: ${{ env.DOCKER_TAG }}
          file: ${{ inputs.file }}
          push: true
#
