name: Deploy-dev

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      file:
        required: false
        type: string
        default: "Dockerfile"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Show repo
        run: github.repository

      - name: Show github
        run: github
#          docker.pkg.github.com/tudorteisanu/shoply/dev


#
#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          name: dist
#
#      - name: Extract artifacts
#        run: tar -xf dist.tar.gz
#
#      - name: Login to Github Packages
#        uses: docker/login-action@v1
#        with:
#          registry: docker.pkg.github.com
#          username: $GITHUB_ACTOR
#          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
#
#      - name: Build image and push to GitHub Packages
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          tags: ${{ inputs.tags }}
#          push: true
#          file: ${{ inputs.file }}
#
#      - name: Add ssh key
#        run: |
#          set -eu
#          mkdir "$HOME/.ssh"
#          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
#          chmod 600 "$HOME/.ssh/key"
#      - name: Update services
#        shell: bash
#        env:
#          USER: ${{ secrets.user }}
#          HOST: ${{ secrets.host }}
#          DIST: ${{ secrets.dist }}
#        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $USER@$HOST "${DIST}/setup.sh"
