name: Deploy PROD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: deploy

      - name: Extract artifacts
        run: tar -xf deploy.tar.gz

      - name: Set release version
        run: |
          RELEASE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and push package
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ inputs.tags }}
          push: true
          file:  ${{ inputs.tags }}

      - name: Add ssh key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Update services
        shell: bash
        env:
          USER: ${{ secrets.user }}
          HOST: ${{ secrets.host }}
          DIST: ${{ secrets.dist }}
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $USER@$HOST "${DIST}/setup.sh"
