name: "Release"

on:      
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      BOT_ACCESS_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      
      - run: git config user.name 'Release BOT'
      - run: git config user.email 'noreply.release@github.com'

      - name: Release
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          TYPE="patch"
          
          if [[ $COMMIT_MESSAGE =~ "[major]" ]]; then
            TYPE="major"
          elif [[ $COMMIT_MESSAGE =~ "[minor]" ]]; then
            TYPE="minor"
          fi
  
          npm version $TYPE -m "[skip ci]"
          git push origin master

      - name: Get version
        run: |
          export RELEASE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          git tag -a $RELEASE_VERSION -m "Update files for new release '$RELEASE_VERSION'"
          git push origin $RELEASE_VERSION


