name: ""

on:      
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      
      - run: git config user.name 'Release BOT'
      - run: git config user.email 'noreply.release@github.com'

      - name: Install Semversioner
        run: pip install semversioner

      - name: Release
        run: |
          semversioner next-version
          semversioner release
          semversioner changelog > CHANGELOG.md
          export VERSION=$(semversioner current-version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update files for new version '${{ env.VERSION }}' [skip ci]"
          git push origin master

      - name: Create new tag
        run: |
          git tag $VERSION -m "Tagging for release $VERSION"
          git push origin $VERSION

