name: Update services

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: "development"
      releaser:
        required: false
        type: string
        default: "semversioner"
    secrets:
      user:
        required: true
      host:
        required: true
      dist:
        required: true
      key:
        required: true

jobs:
  update-services:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Get version
        run: |
          if [ ${{ inputs.deployment }} = "development" ]; then
            TAG=$(echo $GITHUB_REF | cut -d "/" -f 3)
          else
            if [[ ${{ inputs.releaser }} == 'semversioner' ]] then   
              pip install semversioner
              TAG=$(semversioner current-version)
            else        
              TAG=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
            fi
          fi
          
          echo "VERSION=$TAG" >> $GITHUB_ENV
##
      - name: Add ssh key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Update services
        shell: bash
        env:
          USER: ${{ secrets.user }}
          HOST: ${{ secrets.host }}
          DIST: ${{ secrets.dist }}
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $USER@$HOST "cd $DIST && export VERSION=$VERSION && docker-compose pull && docker-compose up -d"
